name: 'Setup Node Project'
description: 'Common setup steps: checkout, setup node, and install dependencies'

inputs:
  registry-url:
    description: 'NPM registry URL (optional)'
    required: false

runs:
  using: 'composite'
  steps:  
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
        registry-url: ${{ inputs.registry-url }}

    - name: Install Dependencies
      shell: bash
      run: |
        npm ci --ignore-scripts

