name: 'Run Fossa Dependency Analysis'
description: 'Runs Fossa dependency analysis'

inputs:
  api-key:
    description: 'Fossa API key'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Run Fossa Dependency Analysis 🐛
      uses: fossas/fossa-action@8dea2e348349fad66e838ce0b365b044c6bf2011 # v2.0.0
      with:
        api-key: ${{ inputs.api-key }}

