name: Approve and Merge Dependabot PRs

on:
  pull_request_target:
    branches: [ main ]

jobs:
  auto-merge-dependabot:
    uses: ./.github/workflows/shared-auto-merge-dependabot.yml
    secrets: inherit
